In [3]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

Q1: Is there any difference in the data type of variables list_ and array_list? If there is then write a code
    to print the data types of both the variables.
    
Ans:Yes , list_ is simple list whereas arraylist_list is numpyarray
    Refer to the below code

In [4]:
print(type(list_),type(array_list))

<class 'list'> <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
    arra_list.

In [6]:
print("Data types of elements of list_")
for i in list_:
    print(type(i))

print("\nData types of elements of array_list")
for i in array_list:
    print(type(i))

Data types of elements of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements of array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3: Considering the following changes in the variable, 
    array_list:array_list = np.array(object = list_, dtype = int)
    Will there be any difference in the data type of the elements present in both the variables, list_ and
    arra_list? 
    If so then print the data types of each and every element present in both the variables, list_
    and arra_list.

Sol:Yes, there will be difference 
    As list_ have element of data type 'str' whereas arra_list have data type 'numpy.int'(integer) because we use the attribute dtype = int

    

In [14]:
array_list = np.array(object = list_, dtype = int)
print("Data types of elements of list_")
for i in list_:
    print(type(i))

print("\nData types of elements of array_list")
for i in array_list:
    print(type(i))

Data types of elements of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements of array_list
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:

    import numpy as np
    num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
    num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
print("The shape of num_array is ",num_array.shape)
print("The size of num_array is ",num_array.size)

The shape of num_array is  (2, 3)
The size of num_array is  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
mat = np.zeros((3,3),dtype ='int')
print(mat)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
mat = np.eye(5 , dtype ='int')
print(mat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
